### ISSUE TITLE
10. Concepts and examples in Association Dialog must be removable 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Brainweaver#153]
>     10. Bij het ‘associëren’ moeten concepten en voorbeelden makkelijk verwijderd kunnen worden (Het programma bevat nu nog een bug.).

**Comment by richelbilderbeek** [comment]
![2018-07-11-085237_743x636_scrot](https://user-images.githubusercontent.com/2098230/42555210-c8880454-84e7-11e8-82c7-e548676ec7cc.png)

**Comment by richelbilderbeek** [comment]
Just a short time fiddling with it:

 * [ ] Contrain QTreeViewWidget to two levels. Do not allow a third level
 * [ ] With Delete an item can be removed
 * [ ] With arrows left and right an item can be (un)indented

**Comment by richelbilderbeek** [comment]
@JeroenN: here is the job to do. Thanks for you help!

**Comment by richelbilderbeek** [comment]
@JeroenN : please let me know explicitly (again) if you want to do this:

 * If no, let me know.
 * if yes, let me know or put this Issue's Card in the [Project](https://github.com/richelbilderbeek/Brainweaver/projects/1) to the 'Worked on' column

**Comment by JeroenN** [comment]
Yes, I am working on Issue 10.

**Comment by JeroenN** [comment]
I am currently working on a bug, when you drag a concept with an example or examples on to another concept, the examples disappear.
What has to be added to associeer- en cluster-scherm?

**Comment by richelbilderbeek** [comment]
Great! I put that/your Issue in the 'Worked on' column of [the BrainWeaver project](https://github.com/richelbilderbeek/Brainweaver/projects/1).

I assume there are no questions anymore about what needs to be done since our meeting last Friday? If and only if I am incorrect, please let me know.

**Comment by richelbilderbeek** [comment]
I just took a look and AFAICS it is just perfect (under Lubuntu)!

I will put this item under review by the employer.

**Comment by richelbilderbeek** [comment]
From employer:

> Re: commentaar versie 20180801: werkt associeren perfect?
>
>2 August 2018 13:24 6 KB
>
>[...], volgens mij werkt associëren goed. [employer]
