### ISSUE TITLE
Concept's examples do not show completely

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/Brainweaver#180]
When I start BrainweaverDeveloper, press '5. QtEditConcept' the dialog pops up as show below. The four examples should be shown completely. No idea what is causing this regression, but I have never checked explicitly myself either.

![2018-07-19-064428_1920x1080_scrot](https://user-images.githubusercontent.com/2098230/42922153-b94ecc96-8b1f-11e8-9843-f436b22e4256.png)

![2018-07-19-064415_776x463_scrot](https://user-images.githubusercontent.com/2098230/42922152-b92ff460-8b1f-11e8-8dd7-0c559d4eaded.png)

**Comment by richelbilderbeek** [comment]
@JeroenN : I assume you fix this :rainbow: . 

 * If no, let me know.
 * if yes, let me know

**Comment by JeroenN** [comment]
I will fix this. However on my laptop it works without any problems.
Maybe I could try to run it on your laptop to see what causes the problem?

**Comment by richelbilderbeek** [comment]
Uh, why did I have to merge something? Well, whatever, I will:

 * [x] merge work with @JeroenN's
 * [ ] rebuild from scratch,
 * [ ] check if error still occurs
   * [ ] if no, notify @JeroenN and close this Issue 
   * [ ] if yes, notify @JeroenN, cross-compile, send link to Windows executables

**Comment by richelbilderbeek** [comment]
Great! Will

 * [x] merge work with @JeroenN's
 * [ ] rebuild from scratch,
 * [ ] check if error still occurs
   * [ ] if no, notify @JeroenN and close this Issue 
   * [ ] if yes, notify @JeroenN, cross-compile, send link to Windows executables

**Comment by richelbilderbeek** [comment]
Hmm, it works [with Wine](http://richelbilderbeek.nl/ProjectBrainweaverExe20180719.zip), not on my local computer. As the employer uses Windows, consider this 'bug' 'fixed' :+1:
