### ISSUE TITLE
Edit concept/relation dialog's examples must be all visible

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/BrainWeaver#194]
This Issue continues from #157.

On Lubuntu and native Windows, in an 'Edit concept/relation' dialog, not all examples' texts are visible, probably due to **the size of the font being hardcoded**. It is probable that other OSes uses different fonts, are that these are absent altogether! Please use QFontMetrics to use the actual font's size to show the examples.

These are Lubuntu screenshots:

![2018-07-23-143442_776x463_scrot](https://user-images.githubusercontent.com/2098230/43076797-a6102918-8e85-11e8-98f4-1587ed14dde2.png)

![2018-07-23-143503_776x463_scrot](https://user-images.githubusercontent.com/2098230/43076798-a6300dd2-8e85-11e8-8e40-d56d045c9e0c.png)
 
![2018-07-23-143816_776x482_scrot](https://user-images.githubusercontent.com/2098230/43076902-0ffd76fa-8e86-11e8-8581-ae5949e04eb3.png)

**Comment by richelbilderbeek** [comment]
@JeroenN: could you please confirm that you have seen this Issue and if you will be working on this?

**Comment by richelbilderbeek** [comment]
Feedback from employer (from #201):

> [...] Ik heb ook al naar de shift-f2 knop gekeken. In het scherm dat dan verschijnt gaat voorbeelden invoeren nog niet goed in die zin dat in de weergave van de voorbeelden maar twee regels ruimte is. Alles wat je na deze twee regels invoert wordt niet zichtbaar.

**Comment by JeroenN** [comment]
I have seen it and I will be working on it.

**Comment by richelbilderbeek** [comment]
I found this code snippet in `QtConceptMap/qtconceptmaprateconcepttallydialog.cpp`

```
  //From https://stackoverflow.com/questions/9544122
  //  /how-to-word-wrap-text-in-the-rows-and-columns-of-a-qtablewidget
  connect(
    ui->table->horizontalHeader(),
    SIGNAL(sectionResized(int, int, int)),
    ui->table,
    SLOT(resizeRowsToContents())
  );
```

Perhaps that will solve the problem?

**Comment by richelbilderbeek** [comment]
More feedback from the employer:

> Bij het invoeren van voorbeelden in een F2-hulpscherm worden derde
    en hoger ge-nummerde voorbeelden niet afgebeeld. Zie ook eerder
    commentaar.

**Comment by JeroenN** [comment]
What does the employer mean with the shift-f2 window. 

When I click on shift-f2 nothing happens.

**Comment by richelbilderbeek** [comment]
(just for completion's sake: in the 'Edit Concept Map' dialog, when (exactly) one concept or relation is selected, with F2 one modifies the concept/relation)

**Comment by richelbilderbeek** [comment]
Feedback employer:

>     3. Bij concepten zijn maar twee eenregelige voorbeelden zichtbaar. Ik kan in het F2-scherm niet scrollen op de ingevoerde voorbeelden. Uit de PDF blijkt wel dat het programma meer dan twee voorbeelden opslaat.

I assume this is enough info, else one could (1) check under Wine, and (2) I could ask the employer for a screenshot. If I need to do the latter, let me know,

Good luck fixing this :+1:

**Comment by JeroenN** [comment]
A screenshot would really help.

**Comment by richelbilderbeek** [comment]
I'll send an email to employer for a screenshot now.

**Comment by JeroenN** [comment]
I think the font is bigger on ubuntu. I ran the program, that you send in the mail, on my window computer and the font didn't span two lines.
![difference windows and ubuntu](https://user-images.githubusercontent.com/19979856/43579124-481c015a-9651-11e8-9f29-eb86835e5275.png)

**Comment by richelbilderbeek** [comment]
Indeed, from your screenshots, Ubuntu makes the font wider:

![2018-08-02-124157_1920x1080_scrot](https://user-images.githubusercontent.com/2098230/43579262-c4d549f4-9651-11e8-89f2-ee4d8b4f9490.png)

But your screenshots both look fine, which is most important. Let's see what the employer shows us.

**Comment by richelbilderbeek** [comment]
@JeroenN : here is the employer's reply:

> hierbij de gevraagde schermopname. In het popup F2-scherm is te zien dat er 1) twee voorbeelden, a1 en a2, zijn ingevoerd en dat voorbeeld a4 ‘klaar’ staat om te worden ingevoerd. Niet te zien is dat voorbeeld a3 al is ingevoerd. Dit voorbeeld kan ook niet in dit scherm zichtbaar gemaakt worden door te scrollen.

![2 2](https://user-images.githubusercontent.com/2098230/43582205-e28d90f0-965b-11e8-8283-3a9d3b2a8069.png)

**Comment by richelbilderbeek** [comment]
From #259:

> 4. Invoeren voorbeelden bij concepten en relaties is nog niet goed. Allereerst kun je nog steeds niet scrollen in het F2-scherm bij een geactiveerd concept of relatie. Hierdoor kan het voorkomen dat wanneer je een vb ingetypt hebt in dit scherm, dit onzichtbaar wordt op het moment dat je het wilt toevoegen aan de lijst voorbeelden. Deactiveer je dan het geactiveerde concept of relatie en activeer je deze vervolgens daarna weer, dan zijn de ingevoerde voorbeelden wel zichtbaar in het F2-scherm!
